name: phpunit

on:
    pull_request:
        branches:
            - main

jobs:
    phpunit:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
                  tools: composer
                  coverage: none # Disable code coverage caching

            - name: Install dependencies
              # --no-cache: Disables Composer's internal package cache
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run PHPUnit
              # --do-not-cache-result: Prevents PHPUnit from caching test results (test status/order)
              run: vendor/bin/phpunit tests --testdox --colors=always -c phpunit.xml --do-not-cache-result
